// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqpdRjaQFvoBECRh394czwHNWXq0ULGjI',
    appId: '1:82585066607:web:9fdbb47b48a60bfd52c19a',
    messagingSenderId: '82585066607',
    projectId: 'senride-hdmley',
    authDomain: 'senride-hdmley.firebaseapp.com',
    storageBucket: 'senride-hdmley.firebasestorage.app',
    measurementId: 'G-QZE6WD58R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs9gyYEvaJtIbDlIbrgh2hBiubvqOPCOI',
    appId: '1:82585066607:android:53a65387ddf8790552c19a',
    messagingSenderId: '82585066607',
    projectId: 'senride-hdmley',
    storageBucket: 'senride-hdmley.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_M9ghVYOXVvfwfFozGej_GE0lQufpKc0',
    appId: '1:82585066607:ios:2fbd05a6326cd1bb52c19a',
    messagingSenderId: '82585066607',
    projectId: 'senride-hdmley',
    storageBucket: 'senride-hdmley.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_M9ghVYOXVvfwfFozGej_GE0lQufpKc0',
    appId: '1:82585066607:ios:2fbd05a6326cd1bb52c19a',
    messagingSenderId: '82585066607',
    projectId: 'senride-hdmley',
    storageBucket: 'senride-hdmley.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqpdRjaQFvoBECRh394czwHNWXq0ULGjI',
    appId: '1:82585066607:web:1ee5908aa177c41a52c19a',
    messagingSenderId: '82585066607',
    projectId: 'senride-hdmley',
    authDomain: 'senride-hdmley.firebaseapp.com',
    storageBucket: 'senride-hdmley.firebasestorage.app',
    measurementId: 'G-PXYYG1SLFV',
  );
}
